### ISSUE TITLE
Could also use [Crossref](https://search.crossref.org/) to find all the appropriate information.

### ISSUE THREAD

**Issue by vicbab** [vicbab/rtftomd#5]
Could also use [Crossref](https://search.crossref.org/) to find all the appropriate information.

Also, we need [zotero] bibtex formatting for the citation keys (e.g. ``author_shortitle_year``.)

_Originally posted by @vicbab in https://github.com/vicbab/rtftomd/issues/1#issuecomment-1967382733_

**Comment by vicbab** [comment]
https://github.com/zotero/zotero/pull/1582

**Comment by zilto** [comment]
La documentation complète du REST API public peut être trouvée ici https://api.crossref.org/swagger-ui/index.html. Le endpoint le plus utile est probablement `/works/{doi}` https://api.crossref.org/swagger-ui/index.html#/Works/get_works__doi_

**Comment by vicbab** [comment]
Intéressant, je me demande si je devrais implémenter cette fonctionnalité avant d'importer dans Zotero ou après en faisant une extension. Je pense que c'est prévu de rendre ca possible dans Zotero 7. Au pire, on rend le code disponible et ça peut s'adapter en extension plus tard

**Comment by vicbab** [comment]
Update: works
